### ISSUE TITLE
Minor Correction in README and Sample Files for project_vectors_to_lang2

### ISSUE THREAD

**Issue by shyamupa** [mfaruqui/crosslingual-cca#5]
I was trying to use the function ./project_vectors_to_lang2.sh from the repository.
However, I got an error saying "inv requires a square matrix". 
After looking around, I found that the sample files do not have same dimensions, so running the command in the README throws the error.

**Comment by wammar** [comment]
Hi Shyam,

I think the command in the README file is meant to illustrate how the script is to be used. It would be great if you could replace the sample files such that they are of the same dimension. I can easily do this but I won't be able to verify if it fixes the issue or not because I don't have access to matlab at the moment.

**Comment by shyamupa** [comment]
Hi Waleed,

No worries, I checked in matlab and and it fixes the error. You can probably add something in the README to first create another sample file, like so
`
cut -d' ' -f1-41 de-sample.txt > de-sample40.txt
`
and modify the sample command appropriately. I just wanted to document this in case someone else runs into trouble with the README. I have closed the issue.

**Comment by wammar** [comment]
Great, thanks Shyam!
